name: go-sarif lint
on:
  pull_request:
jobs:
  lint:
    name: testing go-sarif
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v4
      with:
        go-version-file: ./go.mod

    - run: make lint