name: go-sarif release
on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    name: releasing go-sarif 
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Release
      uses: goreleaser/goreleaser-action@v2
      with: 
       version: latest
       args: release --clean
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}