name: go-sarif test
on:
  pull_request:
jobs:
  test:
    name: testing go-sarif
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version-file: ./go.mod

    - name: test
      run: make test